### ISSUE TITLE
Authentication to N26 fails

### ISSUE THREAD

**Issue by camyyssa** [aengl/cocoon-ynab#1]
When trying to run the N26 node, I'm getting error 403 (Forbidden)

<img width="189" alt="Screenshot 2019-10-13 at 12 54 34" src="https://user-images.githubusercontent.com/131612/66714594-ab95d700-edb8-11e9-8419-7bd7feed0dca.png">

When looking at the console I see message: 
```
"{"userMessage":{"title":"A second authentication factor is required.","detail":"Please provide your second form of authentication."},"mfaToken":"672f4dec-48ce-43da-872d-1b26510feae8","error_description":"MFA token is required","detail":"MFA token is required","hostUrl":"https://api.tech26.de","type":"mfa_required","error":"mfa_required","title":"A second authentication factor is required.","message":"Please provide your second form of authentication.","userId":"da02a73a-8608-45b5-b3f6-dd0cb83c3a15","status":403}"
```

<img width="748" alt="Screenshot 2019-10-13 at 12 57 14" src="https://user-images.githubusercontent.com/131612/66714615-00d1e880-edb9-11e9-96d0-22e05b3bf181.png">

**Comment by mvmisha** [comment]
N26 implemented two factor authentification, 

see this issue, https://github.com/femueller/python-n26/issues/48

**Comment by aengl** [comment]
@mvmisha Thanks for linking to `python-n26`, I ended up just wrapping their CLI 😁
